services:
  - type: web
    name: vstep-master
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "./start.sh"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.12.9"
      - key: ALLOWED_HOSTS
        value: "learn-vstep.onrender.com,vstep.vietdon.vn"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://learn-vstep.onrender.com,https://vstep.vietdon.vn"
