services:
  - type: web
    name: vstep-master
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn vstep.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.12.9"
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "5432"
      - key: RENDER
        value: "true"
